part of 'crypto_symbols.dart';

Map<String, String> symbols = {
  "1inch": "1inch",
  "aave": "Aave",
  "aca": "Acala Token",
  "ach": "Alchemy Pay",
  "acm": "AC Milan Fan Token",
  "ada": "Cardano",
  "add": "ADD",
  "adx": "Ambire AdEx",
  "adxold": "AdEx Old Token",
  "aergo": "Aergo",
  "agi": "SingularityNET",
  "agix": "SingularityNET Token",
  "agld": "Adventure Gold",
  "aion": "AION",
  "akro": "Akropolis",
  "alcx": "Alchemix",
  "algo": "Algorand",
  "alice": "My Neighbor Alice",
  "alpaca": "Alpaca Finance",
  "alpha": "Alpha Finance Lab",
  "amb": "Ambrosus",
  "amp": "AMP",
  "anc": "Anchor Protocol",
  "ankr": "Ankr",
  "ant": "Aragon",
  "antold": "Old Aragon",
  "any": "Anyswap",
  "api3": "API3",
  "appc": "AppCoins",
  "ar": "Arweave",
  "ardr": "Ardor",
  "ark": "Ark",
  "arn": "Aeron",
  "arpa": "ARPA Chain",
  "asr": "AS Roma Fan Token",
  "ast": "AirSwap",
  "astr": "Astar",
  "ata": "Automata",
  "atd": "Atidium",
  "atm": "Atlético de Madrid Fan Token",
  "atom": "Cosmos",
  "auction": "Auction",
  "audio": "Audius",
  "auto": "Auto",
  "ava": "Travala.com",
  "avax": "Avalanche",
  "axs": "Axie Infinity",
  "axsold": "Axie Infinity Old",
  "badger": "Badger DAO",
  "bake": "BakeryToken",
  "bal": "Balancer",
  "band": "BAND",
  "bar": "FC Barcelona Fan Token BAR",
  "bat": "Basic Attention Token",
  "bcd": "Bitcoin Diamond",
  "bch": "Bitcoin Cash",
  "bcha": "Bitcoin Cash ABC",
  "bchsv": "Bitcoin Cash SV",
  "bcx": "BitcoinX",
  "bdot": "BDOT",
  "beam": "Beam",
  "bel": "Bella Protocol",
  "beta": "Beta Finance",
  "beth": "BETH",
  "bgbp": "BGBP",
  "bico": "Biconomy",
  "bidr": "BIDR",
  "bifi": "Beefy.Finance",
  "bkrw": "Binance KRW",
  "blink": "Blockmason Link",
  "blz": "Bluzelle",
  "bnb": "BNB",
  "bnc": "Bifrost",
  "bnt": "Bancor",
  "bnx": "BinaryX",
  "boba": "BOBA token",
  "bolt": "BOLT",
  "bond": "BarnBridge",
  "bot": "Bounce Token",
  "bqx": "Old Voyager Token",
  "brd": "Bread",
  "btc": "Bitcoin",
  "btcst": "Bitcoin Standard Hashrate Token",
  "btg": "Bitcoin Gold",
  "bts": "BitShares",
  "bttc": "BitTorrent",
  "bttold": "BitTorrent OLD",
  "burger": "Burger Swap",
  "busd": "BUSD",
  "bvnd": "BVND",
  "bzrx": "bZx Protocol",
  "c98": "Coin98",
  "cake": "PancakeSwap",
  "can": "CanYaCoin",
  "cbk": "Cobak",
  "cbm": "Crypto Bonus Miles Token",
  "cdt": "Blox",
  "celo": "Celo",
  "celr": "Celer Network",
  "cfx": "Conflux Network",
  "chat": "ChatCoin",
  "chess": "Tranchess",
  "chr": "Chromia",
  "chz": "Chiliz",
  "city": "Manchester City Fan Token",
  "ckb": "CKB",
  "clv": "Clover Finance",
  "cnd": "Cindicator",
  "cocos": "Cocos-BCX",
  "comp": "Compound",
  "cos": "Contentos",
  "coti": "COTI",
  "cover": "COVER Protocol",
  "coverold": "COVER Protocol Old",
  "cream": "Cream Finance",
  "crv": "Curve",
  "ctk": "CertiK",
  "ctr": "Centra",
  "ctsi": "Cartesi",
  "ctxc": "Cortex",
  "cvc": "Civic",
  "cvp": "PowerPool",
  "cvx": "Convex Finance",
  "dai": "Dai",
  "dar": "Mines of Dalarnia",
  "dash": "Dash",
  "data": "Streamr DATAcoin",
  "dcr": "Decred",
  "dego": "Dego Finance",
  "dent": "DENT",
  "dexe": "DeXe",
  "df": "dForce",
  "dgb": "DigiByte",
  "dia": "DIA",
  "dlt": "Agrello",
  "dnt": "district0x",
  "dock": "DOCK",
  "dodo": "DODO",
  "doge": "Dogecoin",
  "don": "Donnie Finance",
  "dot": "Polkadot",
  "drep": "DREP",
  "drepold": "Old DREP",
  "dusk": "Dusk Network",
  "dydx": "dYdX",
  "easy": "EasyFi",
  "edo": "Eidoo",
  "efi": "Efinity Token",
  "egld": "Elrond eGold",
  "elf": "aelf",
  "eng": "Enigma",
  "enj": "Enjin Coin",
  "ens": "Ethereum Name Service",
  "entrp": "Hut34 Entropy",
  "eon": "EOS Network",
  "eop": "EOSpace",
  "eos": "EOS",
  "eps": "Ellipsis",
  "erd": "Elrond",
  "ern": "Ethernity Chain",
  "etc": "Ethereum Classic",
  "eth": "Ethereum",
  "ethbnt": "BNT Smart Token Relay",
  "evx": "Everex",
  "ez": "EasyFi",
  "farm": "Harvest Finance",
  "fet": "Fetch.AI",
  "fida": "Bonfida",
  "fil": "Filecoin",
  "fio": "FIO Protocol",
  "firo": "Firo",
  "fis": "Stafi",
  "flm": "Flamingo",
  "flow": "Flow",
  "flux": "Flux",
  "for": "ForTube",
  "forth": "Ampleforth Governance Token",
  "front": "Frontier",
  "ftm": "Fantom",
  "ftt": "FTX Token",
  "fuel": "Etherparty",
  "fun": "FunToken",
  "fxs": "Frax Share",
  "gala": "Gala",
  "gas": "NeoGas",
  "ghst": "Aavegotchi",
  "glm": "Golem",
  "glmr": "Glimmer",
  "gno": "Gnosis",
  "gnt": "Golem",
  "go": "GoChain",
  "grs": "Groestlcoin",
  "grt": "The Graph",
  "gtc": "Gitcoin",
  "gto": "Gifto",
  "gvt": "Genesis Vision",
  "gxs": "GXChain",
  "gyen": "GYEN",
  "hard": "Kava Lend",
  "hbar": "Hedera Hashgraph",
  "hc": "HyperCash",
  "hcc": "HealthCare Chain",
  "hegic": "Hegic",
  "high": "Highstreet",
  "hive": "Hive",
  "hnst": "Honest",
  "hnt": "Helium",
  "hot": "Holo",
  "icp": "Internet Computer",
  "icx": "ICON",
  "idex": "IDEX",
  "idrt": "Rupiah Token",
  "ilv": "Illuvium",
  "imx": "Immutable X",
  "inj": "Injective Protocol",
  "ins": "Insolar",
  "iost": "IOST",
  "iota": "MIOTA",
  "iotx": "IoTeX",
  "iq": "Everipedia",
  "iris": "IRISnet",
  "jasmy": "JasmyCoin",
  "jex": "Jex Token",
  "joe": "JOE",
  "jst": "JUST",
  "juv": "Juventus Fan Token",
  "kava": "Kava",
  "keep": "Keep Network",
  "key": "Selfkey",
  "keyfi": "KeyFi",
  "klay": "Klaytn",
  "kmd": "Komodo",
  "knc": "KyberNetwork",
  "kncl": "Kyber Network Crystal Legacy",
  "kp3r": "Keep3rV1",
  "ksm": "Kusama",
  "lazio": "Lazio Fan Token",
  "lba": "Lend Borrow Asset",
  "lend": "Aave",
  "lina": "Linear",
  "link": "ChainLink",
  "lit": "Litentry",
  "loka": "League of Kingdoms",
  "loom": "Loom Network",
  "loomold": "Old Loom Network",
  "lpt": "Livepeer",
  "lrc": "Loopring",
  "lsk": "Lisk",
  "ltc": "Litecoin",
  "lto": "LTO Network",
  "ltoold": "Old LTO network token",
  "lun": "Lunyr",
  "luna": "Terra",
  "ma": "Manta Network",
  "mana": "Decentraland",
  "mask": "Mask Network",
  "matic": "Polygon",
  "mbl": "MovieBloc",
  "mbox": "MOBOX",
  "mc": "Merit Circle",
  "mda": "Moeda Loyalty Points",
  "mdt": "Measurable Data Token",
  "mdx": "Mdex",
  "meetone": "MEETONE",
  "mft": "Mainframe",
  "mina": "Mina",
  "mir": "Mirror Protocol",
  "mith": "Mithril",
  "mkr": "Maker",
  "mln": "Enzyme",
  "mod": "Modum",
  "movr": "Moonriver",
  "mth": "Monetha",
  "mtl": "Metal",
  "mtlx": "Mettalex",
  "nas": "Nebulas",
  "nav": "Navcoin",
  "nbs": "New BitShares",
  "ncash": "Nucleus Vision",
  "near": "NEAR Protocol",
  "nebl": "Neblio",
  "neo": "NEO",
  "nft": "APENFT",
  "nkn": "NKN",
  "nmr": "Numeraire",
  "npxs": "Old Pundi X",
  "nsbt": "Neutrino Token",
  "nu": "NuCypher",
  "nuls": "Nuls",
  "nvt": "NerveNetwork",
  "nxs": "Nexus",
  "oax": "openANX",
  "ocean": "Ocean Protocol",
  "og": "OG Fan Token",
  "ogn": "OriginToken",
  "om": "MANTRA DAO",
  "omg": "OMG Network",
  "omold": "Old MANTRA DAO",
  "one": "Harmony",
  "ong": "Ontology Gas",
  "ont": "Ontology",
  "onx": "OnX.Finance",
  "ooki": "OokiDAO",
  "orn": "Orion Protocol",
  "ost": "OST",
  "oxt": "Orchid",
  "para": "Parallel Finance",
  "pax": "Paxos Standard",
  "paxg": "PAX Gold",
  "people": "ConstitutionDAO",
  "perl": "Perlin",
  "perlold": "Perlin Old Token",
  "perp": "Perpetual Protocol",
  "pha": "Phala.Network",
  "phb": "Phoenix Global",
  "phbv1": "Phoenix Global old",
  "pivx": "PIVX",
  "pla": "PlayDapp",
  "pnt": "pNetwork",
  "poa": "POA Network",
  "poe": "Po.et",
  "pols": "Polkastarter",
  "poly": "Polymath",
  "pond": "Marlin",
  "porto": "FC Porto Fan Token",
  "powr": "PowerLedger",
  "ppt": "Populous",
  "prom": "Prometeus",
  "pros": "Prosper",
  "psg": "Paris Saint-Germain Fan Token",
  "pundix": "Pundi X",
  "purse": "Pundi X PURSE",
  "pyr": "Vulcan Forged PYR",
  "pyrold": "Vulcan Forged PYR Old",
  "qi": "BENQI",
  "qiswap": "QiSwap",
  "qkc": "QuarkChain",
  "qlc": "QLC Chain",
  "qnt": "Quant",
  "qsp": "Quantstamp",
  "qtum": "Qtum",
  "quick": "QuickSwap",
  "rad": "Radicle",
  "ramp": "RAMP",
  "rare": "SuperRare",
  "ray": "Raydium",
  "rcn": "Ripio Credit Network",
  "rdn": "Raiden Network Token",
  "reef": "Reef Finance",
  "ren": "Ren",
  "renbtc": "renBTC",
  "rep": "Augur v2",
  "repv1": "Augur",
  "req": "Request Network",
  "rgt": "Rari Governance Token",
  "rif": "RSK Infrastructure Framework",
  "rlc": "iExecRLC",
  "rndr": "Render Token",
  "rose": "Oasis Network",
  "rsr": "Reserve Rights",
  "rune": "THORChain",
  "rvn": "Ravencoin",
  "salt": "Salt",
  "sand": "The Sandbox",
  "santos": "Santos FC Fan Token",
  "sbtc": "Super Bitcoin",
  "sc": "Siacoin",
  "scrt": "Secret",
  "sfp": "SafePal",
  "sgb": "Songbird",
  "sgt": "snglsDAO Governance Token",
  "shib": "SHIBA INU",
  "skl": "SKALE Network",
  "sky": "Skycoin",
  "slp": "Smooth Love Potion",
  "slpold": "Small Love Potion Old",
  "sngls": "Breaker",
  "snm": "SONM",
  "snmold": "SONM OLD",
  "snt": "Status",
  "snx": "Synthetix Network Token",
  "sol": "Solana",
  "solo": "Sologenic",
  "sparta": "Spartan Protocol",
  "spartaold": "Spartan Protocol Old",
  "spell": "Spell Token",
  "srm": "Serum",
  "ssv": "SSV Token",
  "steem": "Steem",
  "stmx": "StormX",
  "storj": "Storj",
  "storm": "Storm",
  "stpt": "Standard Tokenization Protocol",
  "strax": "Stratis",
  "stx": "Stacks",
  "sub": "Substratum",
  "sun": "SUN",
  "sunold": "SUN OLD",
  "super": "SuperFarm",
  "susd": "sUSD",
  "sushi": "Sushi",
  "swrv": "Swerve",
  "sxp": "Swipe",
  "sys": "Syscoin",
  "tct": "TokenClub Token",
  "tfuel": "Theta Fuel",
  "theta": "Theta Token",
  "tko": "Tokocrypto",
  "tlm": "Alien Worlds",
  "tomo": "TomoChain",
  "torn": "Tornado Cash",
  "trb": "Tellor Tributes",
  "tribe": "Tribe",
  "trig": "Triggers",
  "troy": "Troy",
  "tru": "TrueFi",
  "trx": "TRON",
  "tusd": "TrueUSD",
  "tvk": "Terra Virtua",
  "twt": "Trust Wallet Token",
  "uft": "UniLend",
  "uma": "UMA",
  "und": "Unification",
  "unfi": "Unifi Protocol DAO",
  "uni": "Uniswap",
  "usdc": "USD Coin",
  "usdp": "Pax Dollar",
  "usds": "StableUSD",
  "usdt": "TetherUS",
  "ust": "TerraUSD",
  "utk": "Utrust",
  "vai": "Vai",
  "vet": "VeChain",
  "vgx": "Voyager Token",
  "via": "Viacoin",
  "vib": "Viberate",
  "vidt": "VIDT Datalink",
  "vite": "VITE",
  "voxel": "Voxies",
  "vrab": "Verasity",
  "vrt": "Venus Reward Token",
  "vtho": "VeThor Token",
  "wabi": "TAEL",
  "wan": "Wanchain",
  "waves": "Waves",
  "waxp": "WAX",
  "wbnb": "Wrapped BNB",
  "wbtc": "Wrapped Bitcoin",
  "weth": "Wrapped Ether",
  "win": "WINK",
  "wing": "Wing Token",
  "wings": "WINGS",
  "wnxm": "Wrapped NXM",
  "woo": "WOO Network",
  "wrx": "WazirX",
  "wsol": "Wrapped SOL",
  "wtc": "Walton",
  "xdata": "Streamr XDATA",
  "xec": "eCash",
  "xem": "NEM",
  "xlm": "Stellar Lumens",
  "xmr": "Monero",
  "xno": "Nano",
  "xpr": "Proton",
  "xrp": "Ripple",
  "xtz": "Tezos",
  "xvg": "Verge",
  "xvs": "Venus",
  "xym": "Symbol",
  "yfi": "yearn.finance",
  "yfii": "DFI.Money",
  "ygg": "Yield Guild Games",
  "yoyo": "YOYOW",
  "zec": "Zcash",
  "zen": "Horizen",
  "zil": "Zilliqa",
  "zrx": "0x",
  "1inchdown": "1INCHDOWN",
  "1inchup": "1INCHUP",
  "aavedown": "AAVEDOWN",
  "aaveup": "AAVEUP",
  "adadown": "ADADOWN",
  "adaup": "ADAUP",
  "bchdown": "BCHDOWN",
  "bchup": "BCHUP",
  "bnbdown": "BNBDOWN",
  "bnbup": "BNBUP",
  "btcdown": "BTCDOWN",
  "btcup": "BTCUP",
  "dotdown": "DOTDOWN",
  "dotup": "DOTUP",
  "eosdown": "EOSDOWN",
  "eosup": "EOSUP",
  "ethdown": "ETHDOWN",
  "ethup": "ETHUP",
  "fildown": "FILDOWN",
  "filup": "FILUP",
  "grtdown": "GRTDOWN",
  "grtup": "GRTUP",
  "linkdown": "LINKDOWN",
  "linkup": "LINKUP",
  "ltcdown": "LTCDOWN",
  "ltcup": "LTCUP",
  "sushidown": "SUSHIDOWN",
  "sushiup": "SUSHIUP",
  "sxpdown": "SXPDOWN",
  "sxpup": "SXPUP",
  "trxdown": "TRXDOWN",
  "trxup": "TRXUP",
  "unidown": "UNIDOWN",
  "uniup": "UNIUP",
  "xlmdown": "XLMDOWN",
  "xlmup": "XLMUP",
  "xrpdown": "XRPDOWN",
  "xrpup": "XRPUP",
  "xtzdown": "XTZDOWN",
  "xtzup": "XTZUP",
  "yfidown": "YFIDOWN",
  "yfiup": "YFIUP"
};
